const data: any[] = [
   {
      code: 'AE',
      unicode: 'U+1F1E6 U+1F1EA',
      name: 'United Arab Emirates',
      emoji: '🇦🇪',
   },
   {
      code: 'AF',
      unicode: 'U+1F1E6 U+1F1EB',
      name: 'Afghanistan',
      emoji: '🇦🇫',
   },
   {
      code: 'AL',
      unicode: 'U+1F1E6 U+1F1F1',
      name: 'Albania',
      emoji: '🇦🇱',
   },
   {
      code: 'AM',
      unicode: 'U+1F1E6 U+1F1F2',
      name: 'Armenia',
      emoji: '🇦🇲',
   },
   {
      code: 'AO',
      unicode: 'U+1F1E6 U+1F1F4',
      name: 'Angola',
      emoji: '🇦🇴',
   },
   {
      code: 'AQ',
      unicode: 'U+1F1E6 U+1F1F6',
      name: 'Antarctica',
      emoji: '🇦🇶',
   },
   {
      code: 'AR',
      unicode: 'U+1F1E6 U+1F1F7',
      name: 'Argentina',
      emoji: '🇦🇷',
   },
   {
      code: 'AT',
      unicode: 'U+1F1E6 U+1F1F9',
      name: 'Austria',
      emoji: '🇦🇹',
   },
   {
      code: 'AU',
      unicode: 'U+1F1E6 U+1F1FA',
      name: 'Australia',
      emoji: '🇦🇺',
   },
   {
      code: 'AZ',
      unicode: 'U+1F1E6 U+1F1FF',
      name: 'Azerbaijan',
      emoji: '🇦🇿',
   },
   {
      code: 'BA',
      unicode: 'U+1F1E7 U+1F1E6',
      name: 'Bosnia & Herzegovina',
      emoji: '🇧🇦',
   },
   {
      code: 'BD',
      unicode: 'U+1F1E7 U+1F1E9',
      name: 'Bangladesh',
      emoji: '🇧🇩',
   },
   {
      code: 'BE',
      unicode: 'U+1F1E7 U+1F1EA',
      name: 'Belgium',
      emoji: '🇧🇪',
   },
   {
      code: 'BF',
      unicode: 'U+1F1E7 U+1F1EB',
      name: 'Burkina Faso',
      emoji: '🇧🇫',
   },
   {
      code: 'BG',
      unicode: 'U+1F1E7 U+1F1EC',
      name: 'Bulgaria',
      emoji: '🇧🇬',
   },
   {
      code: 'BH',
      unicode: 'U+1F1E7 U+1F1ED',
      name: 'Bahrain',
      emoji: '🇧🇭',
   },
   {
      code: 'BM',
      unicode: 'U+1F1E7 U+1F1F2',
      name: 'Bermuda',
      emoji: '🇧🇲',
   },
   {
      code: 'BO',
      unicode: 'U+1F1E7 U+1F1F4',
      name: 'Bolivia',
      emoji: '🇧🇴',
   },
   {
      code: 'BR',
      unicode: 'U+1F1E7 U+1F1F7',
      name: 'Brazil',
      emoji: '🇧🇷',
   },
   {
      code: 'BW',
      unicode: 'U+1F1E7 U+1F1FC',
      name: 'Botswana',
      emoji: '🇧🇼',
   },
   {
      code: 'CA',
      unicode: 'U+1F1E8 U+1F1E6',
      name: 'Canada',
      emoji: '🇨🇦',
   },
   {
      code: 'CD',
      unicode: 'U+1F1E8 U+1F1E9',
      name: 'Congo',
      emoji: '🇨🇩',
   },
   {
      code: 'CF',
      unicode: 'U+1F1E8 U+1F1EB',
      name: 'Central African Republic',
      emoji: '🇨🇫',
   },
   {
      code: 'CH',
      unicode: 'U+1F1E8 U+1F1ED',
      name: 'Switzerland',
      emoji: '🇨🇭',
   },
   {
      code: 'CI',
      unicode: 'U+1F1E8 U+1F1EE',
      name: 'Côte d’Ivoire',
      emoji: '🇨🇮',
   },
   {
      code: 'CL',
      unicode: 'U+1F1E8 U+1F1F1',
      name: 'Chile',
      emoji: '🇨🇱',
   },
   {
      code: 'CM',
      unicode: 'U+1F1E8 U+1F1F2',
      name: 'Cameroon',
      emoji: '🇨🇲',
   },
   {
      code: 'CN',
      unicode: 'U+1F1E8 U+1F1F3',
      name: 'China',
      emoji: '🇨🇳',
   },
   {
      code: 'CO',
      unicode: 'U+1F1E8 U+1F1F4',
      name: 'Colombia',
      emoji: '🇨🇴',
   },
   {
      code: 'CR',
      unicode: 'U+1F1E8 U+1F1F7',
      name: 'Costa Rica',
      emoji: '🇨🇷',
   },
   {
      code: 'CU',
      unicode: 'U+1F1E8 U+1F1FA',
      name: 'Cuba',
      emoji: '🇨🇺',
   },
   {
      code: 'CV',
      unicode: 'U+1F1E8 U+1F1FB',
      name: 'Cape Verde',
      emoji: '🇨🇻',
   },
   {
      code: 'CZ',
      unicode: 'U+1F1E8 U+1F1FF',
      name: 'Czechia',
      emoji: '🇨🇿',
   },
   {
      code: 'DE',
      unicode: 'U+1F1E9 U+1F1EA',
      name: 'Germany',
      emoji: '🇩🇪',
   },
   {
      code: 'DK',
      unicode: 'U+1F1E9 U+1F1F0',
      name: 'Denmark',
      emoji: '🇩🇰',
   },
   {
      code: 'DO',
      unicode: 'U+1F1E9 U+1F1F4',
      name: 'Dominican Republic',
      emoji: '🇩🇴',
   },
   {
      code: 'DZ',
      unicode: 'U+1F1E9 U+1F1FF',
      name: 'Algeria',
      emoji: '🇩🇿',
   },
   {
      code: 'EC',
      unicode: 'U+1F1EA U+1F1E8',
      name: 'Ecuador',
      emoji: '🇪🇨',
   },
   {
      code: 'EE',
      unicode: 'U+1F1EA U+1F1EA',
      name: 'Estonia',
      emoji: '🇪🇪',
   },
   {
      code: 'EG',
      unicode: 'U+1F1EA U+1F1EC',
      name: 'Egypt',
      emoji: '🇪🇬',
   },
   {
      code: 'ES',
      unicode: 'U+1F1EA U+1F1F8',
      name: 'Spain',
      emoji: '🇪🇸',
   },
   {
      code: 'ET',
      unicode: 'U+1F1EA U+1F1F9',
      name: 'Ethiopia',
      emoji: '🇪🇹',
   },
   {
      code: 'FI',
      unicode: 'U+1F1EB U+1F1EE',
      name: 'Finland',
      emoji: '🇫🇮',
   },
   {
      code: 'FR',
      unicode: 'U+1F1EB U+1F1F7',
      name: 'France',
      emoji: '🇫🇷',
   },
   {
      code: 'GA',
      unicode: 'U+1F1EC U+1F1E6',
      name: 'Gabon',
      emoji: '🇬🇦',
   },
   {
      code: 'GB',
      unicode: 'U+1F1EC U+1F1E7',
      name: 'United Kingdom',
      emoji: '🇬🇧',
   },
   {
      code: 'GH',
      unicode: 'U+1F1EC U+1F1ED',
      name: 'Ghana',
      emoji: '🇬🇭',
   },
   {
      code: 'GM',
      unicode: 'U+1F1EC U+1F1F2',
      name: 'Gambia',
      emoji: '🇬🇲',
   },
   {
      code: 'GN',
      unicode: 'U+1F1EC U+1F1F3',
      name: 'Guinea',
      emoji: '🇬🇳',
   },
   {
      code: 'GQ',
      unicode: 'U+1F1EC U+1F1F6',
      name: 'Equatorial Guinea',
      emoji: '🇬🇶',
   },
   {
      code: 'GR',
      unicode: 'U+1F1EC U+1F1F7',
      name: 'Greece',
      emoji: '🇬🇷',
   },
   {
      code: 'GW',
      unicode: 'U+1F1EC U+1F1FC',
      name: 'Guinea-Bissau',
      emoji: '🇬🇼',
   },
   {
      code: 'HK',
      unicode: 'U+1F1ED U+1F1F0',
      name: 'Hong Kong SAR China',
      emoji: '🇭🇰',
   },
   {
      code: 'HN',
      unicode: 'U+1F1ED U+1F1F3',
      name: 'Honduras',
      emoji: '🇭🇳',
   },
   {
      code: 'HR',
      unicode: 'U+1F1ED U+1F1F7',
      name: 'Croatia',
      emoji: '🇭🇷',
   },
   {
      code: 'HU',
      unicode: 'U+1F1ED U+1F1FA',
      name: 'Hungary',
      emoji: '🇭🇺',
   },
   {
      code: 'ID',
      unicode: 'U+1F1EE U+1F1E9',
      name: 'Indonesia',
      emoji: '🇮🇩',
   },
   {
      code: 'IE',
      unicode: 'U+1F1EE U+1F1EA',
      name: 'Ireland',
      emoji: '🇮🇪',
   },
   {
      code: 'IN',
      unicode: 'U+1F1EE U+1F1F3',
      name: 'India',
      emoji: '🇮🇳',
   },
   {
      code: 'IQ',
      unicode: 'U+1F1EE U+1F1F6',
      name: 'Iraq',
      emoji: '🇮🇶',
   },
   {
      code: 'IR',
      unicode: 'U+1F1EE U+1F1F7',
      name: 'Iran',
      emoji: '🇮🇷',
   },
   {
      code: 'IS',
      unicode: 'U+1F1EE U+1F1F8',
      name: 'Iceland',
      emoji: '🇮🇸',
   },
   {
      code: 'IT',
      unicode: 'U+1F1EE U+1F1F9',
      name: 'Italy',
      emoji: '🇮🇹',
   },
   {
      code: 'JM',
      unicode: 'U+1F1EF U+1F1F2',
      name: 'Jamaica',
      emoji: '🇯🇲',
   },
   {
      code: 'JO',
      unicode: 'U+1F1EF U+1F1F4',
      name: 'Jordan',
      emoji: '🇯🇴',
   },
   {
      code: 'JP',
      unicode: 'U+1F1EF U+1F1F5',
      name: 'Japan',
      emoji: '🇯🇵',
   },
   {
      code: 'KE',
      unicode: 'U+1F1F0 U+1F1EA',
      name: 'Kenya',
      emoji: '🇰🇪',
   },
   {
      code: 'KP',
      unicode: 'U+1F1F0 U+1F1F5',
      name: 'North Korea',
      emoji: '🇰🇵',
   },
   {
      code: 'KR',
      unicode: 'U+1F1F0 U+1F1F7',
      name: 'South Korea',
      emoji: '🇰🇷',
   },
   {
      code: 'KW',
      unicode: 'U+1F1F0 U+1F1FC',
      name: 'Kuwait',
      emoji: '🇰🇼',
   },
   {
      code: 'KZ',
      unicode: 'U+1F1F0 U+1F1FF',
      name: 'Kazakhstan',
      emoji: '🇰🇿',
   },
   {
      code: 'LB',
      unicode: 'U+1F1F1 U+1F1E7',
      name: 'Lebanon',
      emoji: '🇱🇧',
   },
   {
      code: 'LU',
      unicode: 'U+1F1F1 U+1F1FA',
      name: 'Luxembourg',
      emoji: '🇱🇺',
   },
   {
      code: 'LV',
      unicode: 'U+1F1F1 U+1F1FB',
      name: 'Latvia',
      emoji: '🇱🇻',
   },
   {
      code: 'LY',
      unicode: 'U+1F1F1 U+1F1FE',
      name: 'Libya',
      emoji: '🇱🇾',
   },
   {
      code: 'MA',
      unicode: 'U+1F1F2 U+1F1E6',
      name: 'Morocco',
      emoji: '🇲🇦',
   },
   {
      code: 'MC',
      unicode: 'U+1F1F2 U+1F1E8',
      name: 'Monaco',
      emoji: '🇲🇨',
   },
   {
      code: 'MD',
      unicode: 'U+1F1F2 U+1F1E9',
      name: 'Moldova',
      emoji: '🇲🇩',
   },
   {
      code: 'MK',
      unicode: 'U+1F1F2 U+1F1F0',
      name: 'Macedonia',
      emoji: '🇲🇰',
   },
   {
      code: 'ML',
      unicode: 'U+1F1F2 U+1F1F1',
      name: 'Mali',
      emoji: '🇲🇱',
   },
   {
      code: 'MT',
      unicode: 'U+1F1F2 U+1F1F9',
      name: 'Malta',
      emoji: '🇲🇹',
   },
   {
      code: 'MX',
      unicode: 'U+1F1F2 U+1F1FD',
      name: 'Mexico',
      emoji: '🇲🇽',
   },
   {
      code: 'MY',
      unicode: 'U+1F1F2 U+1F1FE',
      name: 'Malaysia',
      emoji: '🇲🇾',
   },
   {
      code: 'MZ',
      unicode: 'U+1F1F2 U+1F1FF',
      name: 'Mozambique',
      emoji: '🇲🇿',
   },
   {
      code: 'NE',
      unicode: 'U+1F1F3 U+1F1EA',
      name: 'Niger',
      emoji: '🇳🇪',
   },
   {
      code: 'NG',
      unicode: 'U+1F1F3 U+1F1EC',
      name: 'Nigeria',
      emoji: '🇳🇬',
   },
   {
      code: 'NI',
      unicode: 'U+1F1F3 U+1F1EE',
      name: 'Nicaragua',
      emoji: '🇳🇮',
   },
   {
      code: 'NL',
      unicode: 'U+1F1F3 U+1F1F1',
      name: 'Netherlands',
      emoji: '🇳🇱',
   },
   {
      code: 'NO',
      unicode: 'U+1F1F3 U+1F1F4',
      name: 'Norway',
      emoji: '🇳🇴',
   },
   {
      code: 'NP',
      unicode: 'U+1F1F3 U+1F1F5',
      name: 'Nepal',
      emoji: '🇳🇵',
   },
   {
      code: 'NZ',
      unicode: 'U+1F1F3 U+1F1FF',
      name: 'New Zealand',
      emoji: '🇳🇿',
   },
   {
      code: 'OM',
      unicode: 'U+1F1F4 U+1F1F2',
      name: 'Oman',
      emoji: '🇴🇲',
   },
   {
      code: 'PA',
      unicode: 'U+1F1F5 U+1F1E6',
      name: 'Panama',
      emoji: '🇵🇦',
   },
   {
      code: 'PE',
      unicode: 'U+1F1F5 U+1F1EA',
      name: 'Peru',
      emoji: '🇵🇪',
   },
   {
      code: 'PH',
      unicode: 'U+1F1F5 U+1F1ED',
      name: 'Philippines',
      emoji: '🇵🇭',
   },
   {
      code: 'PK',
      unicode: 'U+1F1F5 U+1F1F0',
      name: 'Pakistan',
      emoji: '🇵🇰',
   },
   {
      code: 'PL',
      unicode: 'U+1F1F5 U+1F1F1',
      name: 'Poland',
      emoji: '🇵🇱',
   },
   {
      code: 'PR',
      unicode: 'U+1F1F5 U+1F1F7',
      name: 'Puerto Rico',
      emoji: '🇵🇷',
   },
   {
      code: 'PS',
      unicode: 'U+1F1F5 U+1F1F8',
      name: 'Palestine',
      emoji: '🇵🇸',
   },
   {
      code: 'PT',
      unicode: 'U+1F1F5 U+1F1F9',
      name: 'Portugal',
      emoji: '🇵🇹',
   },
   {
      code: 'PY',
      unicode: 'U+1F1F5 U+1F1FE',
      name: 'Paraguay',
      emoji: '🇵🇾',
   },
   {
      code: 'QA',
      unicode: 'U+1F1F6 U+1F1E6',
      name: 'Qatar',
      emoji: '🇶🇦',
   },
   {
      code: 'RO',
      unicode: 'U+1F1F7 U+1F1F4',
      name: 'Romania',
      emoji: '🇷🇴',
   },
   {
      code: 'RS',
      unicode: 'U+1F1F7 U+1F1F8',
      name: 'Serbia',
      emoji: '🇷🇸',
   },
   {
      code: 'RU',
      unicode: 'U+1F1F7 U+1F1FA',
      name: 'Russia',
      emoji: '🇷🇺',
   },
   {
      code: 'SA',
      unicode: 'U+1F1F8 U+1F1E6',
      name: 'Saudi Arabia',
      emoji: '🇸🇦',
   },
   {
      code: 'SD',
      unicode: 'U+1F1F8 U+1F1E9',
      name: 'Sudan',
      emoji: '🇸🇩',
   },
   {
      code: 'SE',
      unicode: 'U+1F1F8 U+1F1EA',
      name: 'Sweden',
      emoji: '🇸🇪',
   },
   {
      code: 'SG',
      unicode: 'U+1F1F8 U+1F1EC',
      name: 'Singapore',
      emoji: '🇸🇬',
   },
   {
      code: 'SI',
      unicode: 'U+1F1F8 U+1F1EE',
      name: 'Slovenia',
      emoji: '🇸🇮',
   },
   {
      code: 'SK',
      unicode: 'U+1F1F8 U+1F1F0',
      name: 'Slovakia',
      emoji: '🇸🇰',
   },
   {
      code: 'SL',
      unicode: 'U+1F1F8 U+1F1F1',
      name: 'Sierra Leone',
      emoji: '🇸🇱',
   },
   {
      code: 'SM',
      unicode: 'U+1F1F8 U+1F1F2',
      name: 'San Marino',
      emoji: '🇸🇲',
   },
   {
      code: 'SN',
      unicode: 'U+1F1F8 U+1F1F3',
      name: 'Senegal',
      emoji: '🇸🇳',
   },
   {
      code: 'SO',
      unicode: 'U+1F1F8 U+1F1F4',
      name: 'Somalia',
      emoji: '🇸🇴',
   },
   {
      code: 'SS',
      unicode: 'U+1F1F8 U+1F1F8',
      name: 'South Sudan',
      emoji: '🇸🇸',
   },
   {
      code: 'SV',
      unicode: 'U+1F1F8 U+1F1FB',
      name: 'El Salvador',
      emoji: '🇸🇻',
   },
   {
      code: 'SY',
      unicode: 'U+1F1F8 U+1F1FE',
      name: 'Syria',
      emoji: '🇸🇾',
   },
   {
      code: 'SZ',
      unicode: 'U+1F1F8 U+1F1FF',
      name: 'Swaziland',
      emoji: '🇸🇿',
   },
   {
      code: 'TD',
      unicode: 'U+1F1F9 U+1F1E9',
      name: 'Chad',
      emoji: '🇹🇩',
   },
   {
      code: 'TG',
      unicode: 'U+1F1F9 U+1F1EC',
      name: 'Togo',
      emoji: '🇹🇬',
   },
   {
      code: 'TH',
      unicode: 'U+1F1F9 U+1F1ED',
      name: 'Thailand',
      emoji: '🇹🇭',
   },
   {
      code: 'TN',
      unicode: 'U+1F1F9 U+1F1F3',
      name: 'Tunisia',
      emoji: '🇹🇳',
   },
   {
      code: 'TR',
      unicode: 'U+1F1F9 U+1F1F7',
      name: 'Turkey',
      emoji: '🇹🇷',
   },
   {
      code: 'TW',
      unicode: 'U+1F1F9 U+1F1FC',
      name: 'Taiwan',
      emoji: '🇹🇼',
   },
   {
      code: 'TZ',
      unicode: 'U+1F1F9 U+1F1FF',
      name: 'Tanzania',
      emoji: '🇹🇿',
   },
   {
      code: 'UA',
      unicode: 'U+1F1FA U+1F1E6',
      name: 'Ukraine',
      emoji: '🇺🇦',
   },
   {
      code: 'UG',
      unicode: 'U+1F1FA U+1F1EC',
      name: 'Uganda',
      emoji: '🇺🇬',
   },
   {
      code: 'UN',
      unicode: 'U+1F1FA U+1F1F3',
      name: 'United Nations',
      emoji: '🇺🇳',
   },
   {
      code: 'US',
      unicode: 'U+1F1FA U+1F1F8',
      name: 'United States',
      emoji: '🇺🇸',
   },
   {
      code: 'UY',
      unicode: 'U+1F1FA U+1F1FE',
      name: 'Uruguay',
      emoji: '🇺🇾',
   },
   {
      code: 'VA',
      unicode: 'U+1F1FB U+1F1E6',
      name: 'Vatican City',
      emoji: '🇻🇦',
   },
   {
      code: 'VE',
      unicode: 'U+1F1FB U+1F1EA',
      name: 'Venezuela',
      emoji: '🇻🇪',
   },
   {
      code: 'VN',
      unicode: 'U+1F1FB U+1F1F3',
      name: 'Vietnam',
      emoji: '🇻🇳',
   },
   {
      code: 'YE',
      unicode: 'U+1F1FE U+1F1EA',
      name: 'Yemen',
      emoji: '🇾🇪',
   },
   {
      code: 'ZA',
      unicode: 'U+1F1FF U+1F1E6',
      name: 'South Africa',
      emoji: '🇿🇦',
   },
   {
      code: 'ZM',
      unicode: 'U+1F1FF U+1F1F2',
      name: 'Zambia',
      emoji: '🇿🇲',
   },
   {
      code: 'ZW',
      unicode: 'U+1F1FF U+1F1FC',
      name: 'Zimbabwe',
      emoji: '🇿🇼',
   },
];

export default data;
